"""empty message

Revision ID: 193b3281b82e
Revises: 2803795858d3
Create Date: 2020-02-12 21:15:48.506092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193b3281b82e'
down_revision = '2803795858d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_registry', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'url_registry', 'users', ['user_id'], ['_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_registry', type_='foreignkey')
    op.drop_column('url_registry', 'user_id')
    # ### end Alembic commands ###
